apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-settings
data:
  SECRET_API_KEY: {{ .Values.apiKey | b64enc }}
  GROWTHBOOK_API_HOST: {{ .Values.apiHost | b64enc }}
  NODE_ENV: {{ .Values.nodeEnvironment | default "production" | b64enc }}
  CACHE_ENGINE: {{ .Values.cacheEngine | b64enc }}
  CACHE_CONNECTION_URL: {{ .Values.cacheConnectionUrl | b64enc }}
  CACHE_STALE_TTL: {{ .Values.cacheStaleTtl | b64enc }}
  CACHE_EXPIRES_TTL: {{ .Values.cacheExpiresTtl | b64enc }}
  USE_HTTP2: {{ .Values.useHttp2 | toString | b64enc }}
  HTTPS_CERT: {{ .Values.httpsCert | b64enc }}
  HTTPS_KEY: {{ .Values.httpsKey | b64enc }}
  ENABLE_REMOTE_EVAL: {{ .Values.enableRemoteEval | b64enc }}
  MAX_PAYLOAD_SIZE: {{ .Values.maxPayloadSize | b64enc }}
  VERBOSE_DEBUGGING: {{ .Values.verboseDebugging | b64enc }}
  PUBLISH_PAYLOAD_TO_CHANNEL: {{ .Values.horizontalScaling.publishPayloadToChannel | b64enc }}
  {{- if not .Values.redisCluster.enabled }}
  USE_CLUSTER: {{ .Values.redisCluster.enabled | toString | b64enc }}
  CLUSTER_ROOT_NODES: {{ .Values.redisCluster.redisRootNodes | b64enc }}
  CLUSTER_ROOT_NODES_JSON: {{ .Values.redisCluster.redisRootNodesJson | toJson | b64enc }}
  CLUSTER_OPTIONS_JSON: {{ .Values.redisCluster.redisOptionsJson | toJson | b64enc }}
  {{- end }}
  {{- if not .Values.mongoDb.enabled }}
  CACHE_DATABASE_NAME: {{ .Values.mongoDb.databaseName | b64enc }}
  CACHE_COLLECTION_NAME: {{ .Values.mongoDb.collectionName | b64enc }}
  {{- end }}
  {{- if not .Values.streaming.enabled }}
  ENABLE_EVENT_STREAM: {{ .Values.streaming.enabled | toString | b64enc }}
  EVENT_STREAM_MAX_DURATION_MS: {{ .Values.streaming.maxDuration | toString | b64enc }}
  EVENT_STREAM_PING_INTERVAL_MS: {{ .Values.streaming.pingInterval | toString | b64enc }}
  {{- end }}
